apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-vulnerability-scanner-api
spec:
  environments:
    - name: prod
      build:
        from: release
    - name: qa
      build:
        from: master
  components:
    - name: "server"
      src: "."
      dockerfileName: "Dockerfile"
      ports:
        - name: http
          port: 3003
      resources:
        requests:
          memory: "200Mi"
          cpu: "100m"
        limits:
          memory: "1000Mi"
          cpu: "1000m"
      public: true
      secrets:
        - SQL_SERVER
        - SQL_DATABASE
        - SQL_USER
        - SQL_PASSWORD
      environmentConfig:
        - environment: qa
          replicas: 1
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 1
          variables:
            LOG_LEVEL: INFO
        - environment: prod
          replicas: 2
          variables:
            LOG_LEVEL: INFO