apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-vulnerability-scanner-api
spec:
  build:
    useBuildKit: true
  environments:
    - name: prod
      build:
        from: release
    - name: qa
      build:
        from: master
  components:
    - name: "server"
      src: "."
      dockerfileName: "Dockerfile"
      identity:
        azure:
          clientId: 5381b944-c904-4c5d-8672-7cedadaf50af
      ports:
        - name: http
          port: 3003
      resources:
        requests:
          memory: "200Mi"
          cpu: "100m"
        limits:
          memory: "1000Mi"
          cpu: "1000m"
      public: true
      variables:
        TOKEN_AUDIENCE: "6dae42f8-4368-4678-94ff-3960e28e3630"
        TOKEN_ISSUER: https://sts.windows.net/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/
        SQL_USE_FEDERATED: "true"
        PRETTY_PRINT: "false"
        LOG_LEVEL: INFO
        GIN_MODE: release
      secrets:
        - SQL_SERVER
        - SQL_DATABASE
        - SQL_USER
        - SQL_PASSWORD
      environmentConfig:
        - environment: qa
          replicas: 1
        - environment: prod
          replicas: 2
