# yaml-language-server: =https://raw.githubusercontent.com/equinor/radix-operator/release/json-schema/radixapplication.json

apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-vulnerability-scanner-api
spec:
  build:
    useBuildKit: true
  environments:
    - name: prod
      build:
        from: release
    - name: qa
      build:
        from: master
  components:
    - name: "server"
      readOnlyFileSystem: true
      src: "."
      dockerfileName: "Dockerfile"
      runtime:
        architecture: arm64
      identity:
        azure:
          clientId: 5bf4ef3d-6c0b-4eee-89ed-966a897eef6e
      ports:
        - name: http
          port: 3003
      public: true
      resources:
        requests:
          memory: "200Mi"
          cpu: "100m"
        limits:
          memory: "1000Mi"
          cpu: "1000m"
      variables:
        TOKEN_AUDIENCE: "6dae42f8-4368-4678-94ff-3960e28e3630"
        TOKEN_ISSUER: https://sts.windows.net/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/
        PRETTY_PRINT: "false"
        LOG_LEVEL: INFO
        GIN_MODE: release
        SQL_SERVER: sql-radix-vulnerability-scan-dev.database.windows.net
        SQL_DATABASE: radix-vulnerability-scan
      environmentConfig:
        - environment: qa
          replicas: 1
          horizontalScaling:
            maxReplicas: 1
            minReplicas: 0
            triggers:
              - name: cron
                cron:
                  timezone: Europe/Oslo
                  start: 0 7 * * 1-5 # 07:00 Monday - Friday
                  end: 0 17 * * 1-5 # 17:00 Monday - Friday
                  desiredReplicas: 1
        - environment: prod
          replicas: 2
