
name: radix-vulnerability-scanner-api-pr
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      env:
        REF: ${{ github. sha }}
      run: docker build -t radix-vulnerability-scanner-api:${REF##*/} .

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.55.2

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod download
      - name: Run Tests
        run: go test -cover `go list ./...`

  test-swagger:
    name: Test Swagger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --no-tags --no-recurse-submodules --depth=1  origin master:master
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod download
      - name: Install Swagger
        run: go install github.com/go-swagger/go-swagger/cmd/swagger@v0.30.5
      - name: Generate Swagger
        run: swagger generate spec -o ./swagger.json -m -x=github.com/equinor/radix-vulnerability-scanner-api/radix_api/generated_client/models
      - name: Validate no changes
        run: diff swagger.json ./swaggerui/html/swagger.json
      - name: Check breaking changes
        if: always()
        id: breaking
        continue-on-error: true
        run: swagger diff --break <(git show master:swaggerui/html/swagger.json) swagger.json > /tmp/swagger_breaking_changes.txt
      - name: Add comment
        if: failure() && steps.breaking.outcome == 'failure'
        uses: mshick/add-pr-comment@v2
        with:
          message-id: breaking-comment
          preformatted: true
          message-path: /tmp/swagger_breaking_changes.txt

  test-radixconfig:
    name: Test RadixConfig
    runs-on: ubuntu-latest
    steps:
      - name: 'Fake TOKEN FOR RADIX CLI'
        run: echo "APP_SERVICE_ACCOUNT_TOKEN=hello-world" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - run: git fetch --no-tags --no-recurse-submodules --depth=1  origin master:master

      - run: make generate-radixconfig-envs
      - run: git diff --exit-code

      - name: 'Validate C2'
        uses: equinor/radix-github-actions@v1
        with:
          args: validate radix-config --config-file radixconfig.c2.yaml

      - name: 'Validate DEV'
        uses: equinor/radix-github-actions@v1
        with:
          args: validate radix-config --config-file radixconfig.dev.yaml

      - name: 'Validate Playground'
        uses: equinor/radix-github-actions@v1
        with:
          args: validate radix-config --config-file radixconfig.playground.yaml
